local options = {
  formatters_by_ft = {
    lua = { "stylua" },
    asm = { "asmfmt" },
    nasm = { "asmfmt" },
    svelte = { "prettier" },
    astro = { "prettier" },
    cs = { "csharpier" },
    javascript = { "biome" },
    typescript = { "biome" },
    javascriptreact = { "biome" },
    typescriptreact = { "biome" },
    json = { "biome" },
    java = { "google-java-format" },
    vue = { "prettier" },
    graphql = { "prettier" },
    php = { "php_cs_fixer" },
    kotlin = { "ktlint" },
    markdown = { "prettier" },
    erb = { "htmlbeautifier" },
    html = { "htmlbeautifier" },
    proto = { "buf" },
    rust = { "rustfmt" },
    yaml = { "yamlfix" },
    toml = { "taplo" },
    css = { "prettier" },
    c = { "clang-format" },
    cpp = { "clang-format" },
    scss = { "prettier" },
    python = { "ruff" },
    sh = { "beautysh" },
    bash = { "beautysh" },
    zsh = { "beautysh" },
    ruby = { "rubocop" },
    go = { "gofmt", "goimports" },
    xml = { "xmllint" },
  },
}

return options
